import {Appearance} from 'react-native'

const isDarkTheme = Appearance.getColorScheme() === 'dark'

export const Success = isDarkTheme ? '#3ADB76' : '#3ADB76'
export const GrayLight = isDarkTheme ? '#E6E6E6' : '#E6E6E6'
export const Button = isDarkTheme ? '#00AAFF' : '#00AAFF'
export const BottomBorder = isDarkTheme ? '#BFBFBF' : '#BFBFBF'
export const SearchableDropdownBg = isDarkTheme ? '#FAF9F8' : '#FAF9F8'
export const SearchableBorder = isDarkTheme ? '#BBB' : '#BBB'

// export const LabelText = defaultTheme2 ? '#696969' : '#FFFEFD'
export const Description = isDarkTheme ? '#5F5F5F' : '#5F5F5F'
export const CardbackGround = isDarkTheme ? '#EfEfEf' : '#EfEfEf'
export const DesignationText = isDarkTheme ? '#1C3232' : '#1C3232'
export const placeholderTextColor = isDarkTheme ? '#ADB5BD' : '#ADB5BD'
export const placeholderContainer = isDarkTheme ? '#dddddd' : '#dddddd'
export const searchableTextColor = isDarkTheme ? '#2F3838' : '#2F3838'
export const DarkGrey = isDarkTheme ? '#5A5A5A' : '#5A5A5A'
export const Purple = isDarkTheme ? '#ab42b3' : '#ab42b3'

//colors added by abdullah

export const EvenGreen_80 = isDarkTheme ? '#153232' : '#153232'
export const DarkPepper_80 = isDarkTheme ? '#131C1C' : '#131C1C'
export const DarkPepper_60 = isDarkTheme ? '#2F3838' : '#2F3838'
export const DarkPepper_40 = isDarkTheme ? '#4C5555' : '#4C5555'
export const DarkPepper_20 = isDarkTheme ? '#9CA4A4' : '#9CA4A4'
export const LightCream_80 = '#DEDBD4'
export const LightCream_60 = isDarkTheme ? '#EAE8E1' : '#EAE8E1'
export const LightCream_40 = isDarkTheme ? '#F5F3ED' : '#F5F3ED'
export const LightCream_20 = isDarkTheme ? '#FCF8FF' : '#FCF8FF'
export const LightCream_10 = isDarkTheme ? '#FFFEFD' : '#FFFEFD'

//ignore theme Colors
export const LightCream_10_L = isDarkTheme ? '#FFFEFD' : '#FFFEFD'
export const Shadow_Color = isDarkTheme ? '#000000' : '#000000'
export const IBlack = '#000000'
export const ILightCream_10 = '#FFFEFD'
export const Neon_Blue = '#4294e6'
export const ILightCream_10_1 = isDarkTheme ? '#FFFEFD' : '#FFFEFD'

//Gamba
export const LimeGreen = isDarkTheme ? '#32CD32' : '#32CD32'

export const BackgroundColor = isDarkTheme ? '#F8FBFF' : '#F8FBFF'
export const SubTitleColor = isDarkTheme ? '#191c25' : '#191c25'
export const LightGreen = isDarkTheme ? '#32CD32' : '#32CD32'
export const OrangeColor = isDarkTheme ? '#F85708' : '#F85708'
export const MainThemeColor = isDarkTheme ? '#38B000' : '#38B000'
export const GrayminusColor = isDarkTheme ? 'rgb(164, 164, 164)' : 'rgb(164, 164, 164)'
export const PriceColor = '#ff5d3a'
export const LightYellow = '#f8e897'
export const Yellow = '#ffbc00'

export const tradeColor = '#22c8a3'
export const donationColor = '#00be03'
export const saleColor = '#ffba00'
export const productColor = '#ff5b00'

export const Green = 'green'
export const Blue = '#1366FF'
export const ActiveBtColor = isDarkTheme ? '#32CD32' : '#32CD32'
export const DisableBtColor = isDarkTheme ? '#38B000' : '#38B000'

export const HTextColor = isDarkTheme ? '#32CD32' : '#32CD32'
export const TextBlack = isDarkTheme ? '#000000' : '#000000'
export const SearchBackgorund = isDarkTheme ? '#FCF8FF' : '#FCF8FF'
export const White = isDarkTheme ? '#ffffff' : '#ffffff'
export const Black = isDarkTheme ? '#000000' : '#000000'
export const TextGray = isDarkTheme ? '#8E969D' : '#8E969D'
export const IconsColor = isDarkTheme ? '#32CD32' : '#32CD32'
export const BorderGrey = isDarkTheme ? '#efeff0' : '#efeff0'
export const InputIconNormal = isDarkTheme ? '#9e9e9e' : '#9e9e9e'
export const BorderColor = isDarkTheme ? '#A1E8A1' : '#A1E8A1'
export const BorderColorDark = isDarkTheme ? '#175E17' : '#175E17'
export const ErrorBorder = isDarkTheme ? '#F46A6A' : '#F46A6A'
export const ErrorText = isDarkTheme ? '#F46A6A' : '#F46A6A'
export const CardBg = isDarkTheme ? '#FBFBFB' : '#FBFBFB'
export const SearchableText = isDarkTheme ? '#525252' : '#525252'
export const RedColor = isDarkTheme ? '#FF0000' : '#FF0000'
export const YellowColor = isDarkTheme ? '#FFBD00' : '#FFBD00'
export const SearchBG = isDarkTheme ? '#F8F9FA' : '#F8F9FA'
export const BlueColor = isDarkTheme ? '#2667FF' : '#2667FF'
export const LightGrayColor = isDarkTheme ? '#6C757D' : '#6C757D'
export const LightMainColor = isDarkTheme ? '#D8EFCC' : '#D8EFCC'
export const LightestMainColor = isDarkTheme ? '#EBF7E4' : '#EBF7E4'
export const UreadDot = isDarkTheme ? '#59C1F2' : '#59C1F2'
